### ISSUE TITLE
Loading messages is inconsistent

### ISSUE THREAD

**Issue by davidbarratt** [wikimedia/banana-i18n#12]
If you have a object of messages like:
```javascript
const messages = {
  en: {
    test: 'TEST'
  }
};
```
And you do something like this:
```javascript
new Banana( 'es', { messages }):
```
or even
```javascript
const banana = new Banana( 'es' ):
banana.load(messages);
```
the messages will not be loaded correctly.

The only way to correctly load them is like this:
```javascript
const banana = new Banana();
banana.load(messages)
banana.setLocale('es');
```

I think this is goofy. I'm not really sure how to fix it other than to not use the locale that has been set when loading messages, but then perhaps the constructor should not accept messages either.

Alternatively, it could just not accept multiple locals, or we could say that you __must__ provide an object with the locals as the keys (and __always__ accept multiple locales). (which would be my preference). 

Regardless, I think the set locale should only apply to parsing, not loading.

**Comment by santhoshtr** [comment]
I added the following test. This should clarify it

```
 it('should respect finalFallback option', () => {
    const banana = new Banana('es', {
      messages: {
        ml: {
          message_1: 'ഒന്നാമത്തെ മെസ്സേജ്',
          message_2: 'രണ്ടാമത്തെ മെസ്സേജ്'
        },
        en: {
          message_1: 'Message one',
          message_2: 'Message two'
        }
      },
      finalFallback: 'ml'
    })
    assert.ok(!banana.messageStore.hasLocale('es'))
    assert.ok(banana.messageStore.hasLocale('en'))
    assert.ok(banana.messageStore.hasLocale('ml'))
    assert.strictEqual(banana.i18n('message_2'), 'രണ്ടാമത്തെ മെസ്സേജ്')
})

```

The message object has no `es` messages. The current locale is `es`. You can see that the fallback chain is followed. The given messages are loaded properly and  you get the expected message.

**Comment by davidbarratt** [comment]
that looks good to me! I'll give it a whirl and let you know how it goes!
