### ISSUE TITLE
Library target is UMD which prevents library from being used in node.js

### ISSUE THREAD

**Issue by davidbarratt** [wikimedia/banana-i18n#14]
When I attempt to use this library in node.js I recieve the following error:
> ReferenceError: window is not defined at Object.<anonymous> (/Users/dbarratt/Sites/wikimedia/interaction-timeline/next/node_modules/banana-i18n/dist/banana-i18n.js:1:194)

This seems to be because the [libraryTarget](https://webpack.js.org/configuration/output/#outputlibrarytarget) is `umd` instead of `commonjs2`

**Comment by santhoshtr** [comment]
New version released https://github.com/wikimedia/banana-i18n/releases/tag/v1.1.0
