### ISSUE TITLE
Move to Wikimedia?

### ISSUE THREAD

**Issue by davidbarratt** [wikimedia/banana-i18n#2]
https://github.com/santhoshtr/banana-i18n/blob/d7beedcaa116814ed8528dd90621fc13fd7134db/package.json#L2

Will this package be moved to @wikimedia? If so, you could prefix the package with `@wikimedia/` otherwise it's fine the way it is.

**Comment by santhoshtr** [comment]
I don't hae repo creation permission in @wikimedia. Will ask others

**Comment by santhoshtr** [comment]
Also no credentials for publishing in @wikimedia npm organization

**Comment by davidbarratt** [comment]
You can request a new repository here:
https://www.mediawiki.org/wiki/Gerrit/New_repositories
based on:
https://www.npmjs.com/settings/wikimedia/members
it looks like @catrope, @jdforrester, @krinkle can give you access to publish under the organization.

**Comment by santhoshtr** [comment]
@Krinkle Can I request to add me to the group of owners of Wikimedia github org?
I had no plans to put this repo in Gerrit :)

**Comment by Krinkle** [comment]
@santhoshtr I've enabled the repo creation and transfer rights. I'm not opposing administrator privileges, but I'm unfamiliar with the process for granting those, so I've held off on that for now.

**Comment by santhoshtr** [comment]
Transferred to https://github.com/wikimedia/banana-i18n
