### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by bitPogo** [wikimedia/banana-i18n#24]
Since some projects in the mw environment, which are using typescript, could profit from this lib, if it would provide type definitions. Is there any plan to do that, or a wish for contribution in this particular manor.

**Comment by santhoshtr** [comment]
That would be a good idea. Any contribution in this area is much appreciated.

**Comment by bitPogo** [comment]
Please see: https://github.com/wikimedia/banana-i18n/pull/25 for my contribution.

**Comment by bitPogo** [comment]
Done since #25 is merged
