### ISSUE TITLE
Return null instead of the message key

### ISSUE THREAD

**Issue by davidbarratt** [wikimedia/banana-i18n#34]
Would it be possible to return `null` instead of the message key here?
https://github.com/wikimedia/banana-i18n/blob/a120a55cb1315975281212ca86cd3b7b5ff19b62/src/index.js#L66

Maybe add a config parameter? It would be helpful to return `null` instead of having a flash of the message key if the messages haven't been loaded yet.

**Comment by santhoshtr** [comment]
Returning the message key as such was done to make the behavior compatible with MediaWiki mw.msg from where the whole library originated.

I think a config parameter make sense. Would you like submit a patch?

**Comment by davidbarratt** [comment]
Sure. Maybe an empty string would be better than null?

**Comment by santhoshtr** [comment]
Yeah, empty string may be better
