### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by davidbarratt** [wikimedia/banana-i18n#4]
This doesn't appear to be on npm:
https://www.npmjs.com/package/banana-i18n

Also, should probably create a version. :)

**Comment by santhoshtr** [comment]
Yes, planning to do that. But multiple issues- I am not owner of this repo since it is transferred to wikimedia github account. Need to ask others. Also I did not get wikimedia npm organization access. I guess I will publish using my personal npm account

**Comment by santhoshtr** [comment]
https://www.npmjs.com/package/banana-i18n
