### ISSUE TITLE
Is `{{GENDER:||e}}` valid syntax?

### ISSUE THREAD

**Issue by stephanebisson** [wikimedia/banana-i18n#41]
This is the French translation of a message we've seen recently in the KaiOS app: `Êtes-vous sûr{{GENDER:||e}} de vouloir quitter ? Tout votre avis sera perdu`

While the gender of the user would be useful here it cannot be provided by the app. The GENDER function was not used in the English message and no parameter was provided or documented.

This caused a crash of the app in production. We've added a try/catch around our usage of the library to prevent that in the future.

Just thought we'd let you know in case you want to think about different ways to handle cases like that.

**Comment by Nikerabbit** [comment]
In MediaWiki (core) that means use the gender for current user, and print `e` if it's female. Translators are not supposed to use such things if they are not documented to be supported.

**Comment by santhoshtr** [comment]
Some of the mediawiki specific grammars cannot be supported here because this library is not dependent on it. User related functions like gender as in this issue is one example. Other than uncaught error, I am not sure if there is any sensible fallback behavior in this library is possible.

**Comment by stephanebisson** [comment]
Agreed. In the application we try to fall back gracefully but in this library throwing an error makes sense.
