### ISSUE TITLE
banana-18n is not working with IE11

### ISSUE THREAD

**Issue by jaypatel711** [wikimedia/banana-i18n#44]
banana-i18n is not working on Internet Explorer 11.

Error Type:

SCRIPT1002: Syntax error
banana-i18n.js (1,4147)

**Comment by siddharthvp** [comment]
Yes it won't work. [Intl.PluralRules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules) introduced in https://github.com/wikimedia/banana-i18n/commit/61b0b9cddcc2f06f440a8e3480ae5273dcb7b999 isn't supported in IE.

**Comment by santhoshtr** [comment]
Correct. Not planning to support IE11. The previous i18n library -[ jquery.i18n](https://github.com/wikimedia/jquery.i18n/) provides IE support.  Earler version of this library before 61b0b9c is also an option
