### ISSUE TITLE
fallbacks.json file is outdated?

### ISSUE THREAD

**Issue by siddharthvp** [wikimedia/banana-i18n#49]
The [fallbacks.json file](https://github.com/wikimedia/banana-i18n/blob/master/src/languages/fallbacks.json) has only 164 entries. On running @Nikerabbit's grep command mentioned in https://phabricator.wikimedia.org/T258492#6490574 on an up-to-date mediawiki clone, the file generated is [this](https://github.com/jwbth/convenient-discussions/blob/master/language-fallbacks.json) which has 240 entries.

**Comment by santhoshtr** [comment]
Yes, they are outdated. Thanks in advance if you like to submit a PR.

**Comment by siddharthvp** [comment]
Opened #54.
