### ISSUE TITLE
Provide a method to set the locale after construction

### ISSUE THREAD

**Issue by davidbarratt** [wikimedia/banana-i18n#9]
There is no way to change the locale after a `Banana` object has been constructed. One could change the `local` property, but they would also have to update the `parser` object as well. It would be helpful if a method was provided to do this so the whole thing doesn't have to be recreated to change the locale.

**Comment by santhoshtr** [comment]
Added setLocale method

https://github.com/santhoshtr/banana-i18n/blob/master/src/index.js#L30
